CREATE OR REPLACE TABLE persornal-projects.crimes.stg_crime_chicago (
  unique_key            INT64     OPTIONS(description="Unique identifier for the record."),
  case_number           STRING    OPTIONS(description="Police department case number."),
  case_date             TIMESTAMP OPTIONS(description="Date and time of the incident."),
  block                 STRING    OPTIONS(description="Address block where the incident occurred."),
  iucr                  STRING    OPTIONS(description="Illinois Uniform Crime Reporting code."),
  primary_type          STRING    OPTIONS(description="Primary crime category."),
  description           STRING    OPTIONS(description="The subcategory of the primary description."),
  location_description  STRING    OPTIONS(description="Location where the crime occurred (e.g., STREET, RESIDENCE)."),
  arrest                BOOL      OPTIONS(description="True if an arrest was made."),
  domestic              BOOL      OPTIONS(description="True if the incident was domestic-related."),
  beat                  INT64     OPTIONS(description="The beat (subdivision of district) where the incident happened."),
  district              INT64     OPTIONS(description="Indicates the police district where the incident occurred."),
  ward                  INT64     OPTIONS(description="Political ward where the incident occurred."),
  community_area        INT64     OPTIONS(description="Chicago community area code."),
  fbi_code              STRING    OPTIONS(description="FBI crime classification code."),
  x_coordinate          FLOAT64   OPTIONS(description="X coordinate in State Plane coordinate system."),
  y_coordinate          FLOAT64   OPTIONS(description="Y coordinate in State Plane coordinate system."),
  year                  INT64     OPTIONS(description="Year the incident occurred."),
  updated_on            TIMESTAMP OPTIONS(description="Last update timestamp."),
  latitude              FLOAT64   OPTIONS(description="Latitude of the incident location."),
  longitude             FLOAT64   OPTIONS(description="Longitude of the incident location."),
  location              STRING    OPTIONS(description="Formatted location string."),
  ingestion_time        TIMESTAMP OPTIONS(description="The timestamp when the data was ingested into the staging table. | Thailand timezone (UTC+7)")
);
